# Generated by Django 4.1.6 on 2023-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_mining_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataToCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
